highlighter: false
markdown: rdiscount
permalink: /:year/:month/:day/:title/
paginate: 5
name: Nathan Totten's Blog
description: Thoughts and Experiences with Software Development.
url: http://ntotten.com
gems: [jekyll-paginate]
