# Site settings
title: Nathan Totten
description: Thoughts and Experiences with Software Development.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ntotten.com
twitter_username: ntotten
github_username:  ntotten

# Build settings
permalink: /:year/:month/:day/:title/
markdown: kramdown
gems:
  - jekyll-redirect-from
