markdown: rdiscount
pygments: false
permalink: /:year/:month/:day/:title/
paginate: 5
version: 45d475bc-1e36-4b5d-9d9d-7a07fcd94d50
name: Nathan Totten's Blog
description: Thoughts and Experiences with Software Development.
url: http://ntotten.com